name: Send WhatsApp Message on Main Branch Commit

on:
  push:
    branches:
      - main

jobs:
  send_whatsapp:
    runs-on: ubuntu-latest

    steps:
      # Faz o checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Gera o link de WhatsApp e imprime no log
      - name: Generate WhatsApp Link
        run: |
          PHONE_NUMBER="+5513992084000"
          MESSAGE="Novo commit na branch main! Acesse o repositório para mais detalhes."
          WHATSAPP_URL="https://wa.me/${PHONE_NUMBER}?text=$(echo $MESSAGE | jq -sRr @uri)"
          echo "Acesse o seguinte link para enviar a mensagem pelo WhatsApp: $WHATSAPP_URL"
