name: Send WhatsApp Message on Main Branch Commit

on:
  push:
    branches:
      - main

env:
  TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
  TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
  TWILIO_PHONE_NUMBER: ${{ secrets.TWILIO_PHONE_NUMBER }}
  RECIPIENT_PHONE_NUMBER: ${{ secrets.RECIPIENT_PHONE_NUMBER }}

jobs:
  send_whatsapp:
    runs-on: ubuntu-latest

    steps:
      # Faz o checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Gera o link de WhatsApp e imprime no log
      - name: Generate WhatsApp Link
        run: |
          PHONE_NUMBER="+5513992084000"
          MESSAGE="Novo commit na branch main! Acesse o repositório para mais detalhes."
          WHATSAPP_URL="https://wa.me/${PHONE_NUMBER}?text=$(echo $MESSAGE | jq -sRr @uri)"
          echo "Acesse o seguinte link para enviar a mensagem pelo WhatsAp: $WHATSAPP_URL"
  send_whatsapp-twilio:
    runs-on: ubuntu-latest

    steps:
      # Envia mensagem de WhatsApp
      - name: 'Send WhatsApp message'
        uses: twilio-labs/actions-sms@v1
        with:
          fromPhoneNumber: '$TWILIO_PHONE_NUMBER' # alternatively, use a Repository Secret
          toPhoneNumber: '$RECIPIENT_PHONE_NUMBER' # alternatively, use a Repository Secret
          message: 'Hello from Twilio'
